### ISSUE TITLE
Support for reversed animation

### ISSUE THREAD

**Issue by martin-g** [ractivejs/ractive-transitions-fly#4]
Hi,

I need to create an effect of going forward and backward.
There are several "panels" which are swapped with "Back" and "Continue" buttons.
Clicking on "Continue" moves the current panel to the left and hides it. The new panel appears from the right of the screen and positions itself (at the center).
Clicking on "Back" I need the opposite transformation: the current panel hides in the right, and the previous one appears from the left.

I believe the solution is as simple as negating the value of `x` parameter.
But with the current way of defining the effect parameters (`x` and `y`) by using just `intro` and `outro` attributes I don't see how to set the extra custom parameter (`reverse: true|false`) for the different buttons.

Do you have an idea how this could be accomplished ?

**Comment by martin-g** [comment]
Negating the `x` parameter indeed does the job!

I've added (ugly, I know!) to ractive-transitions-fly.js:
````javascript
if (Ractive.flyNegate) {
	params.x = -params.x;
	params.y = -params.y;
}
````

and then my method for changing the steps is:
````javascript
goToStep: function(event, step) {
  var currentStep = that.get('step');
  Ractive.flyNegate = currentStep < step;

  that.set( 'step', null ).then( function () {
    that.set( 'step', step );
  });
}
````

This does the job

**Comment by martypdx** [comment]
You can do that in the declaration using a javascript expression:

```html
<div intro='fly:{ x: step < current ? -100 : 100 }'></div>
```

**Comment by martin-g** [comment]
could you please expand on this ?
I have a member `step`of the Ractive's instance `data`.
My custom function `goToStep` receives a parameter (accidently named also 'step') that is the step to go to.
How I can make those available in the context of evaluating the fly's parameters ?

I've tried your suggestion but obviously it doesn't work. I can imagine that Ractive using the data's `step`, but I cannot imagine how `current` will be mapped to the function parameter `step`.

**Comment by martypdx** [comment]
Maybe with your setup, do something like:

```js
goToStep: function(event, step) {
  var currentStep = that.get('step');
  that.set({
    direction: (currentStep < step) ? -1 : 1,
    step: null
  }).then( function () {
    that.set( 'step', step );
  });
}
```
And then use those `direction` accordingly (I don't remember off the top of my head if you need to reverse the direction for outro, but you get the idea):

```html
<div intro='fly:{ x: direction * 100 }' outro='fly:{ x: -direction * 100 }'></div>
```
````

**Comment by martin-g** [comment]
Something is not correct.
I see with the debugger that the value of `direction` changes from `1` to `-1` in `goToStep()` but then it seems is not used for the calculation.

**Comment by martin-g** [comment]
Further debugging shows that at `processParams.js` comes as String: `"{x: direction * 100}"`.
It seems there a call to JSON.parse() earlier that fails and the string is passed to processParams.js for further processing.

**Comment by martypdx** [comment]
Sorry about that, decorator arguments need to be mustached:

```html
<div intro='fly:{ x: {{direction * 100}} }' outro='fly:{ x: {{-direction * 100}} }'></div>
```

**Comment by martin-g** [comment]
Thank you, sir!
That made it!
